// +build !ignore_autogenerated

/*
 * This file is part of the KubeVirt project
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * Copyright 2018 Red Hat, Inc.
 *
 */

// Code generated by deepcopy-gen. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/api/core/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BareMetalMachineProviderConfig) DeepCopyInto(out *BareMetalMachineProviderConfig) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	if in.FencingConfig != nil {
		in, out := &in.FencingConfig, &out.FencingConfig
		if *in == nil {
			*out = nil
		} else {
			*out = new(FencingConfig)
			(*in).DeepCopyInto(*out)
		}
	}
	if in.Roles != nil {
		in, out := &in.Roles, &out.Roles
		*out = make([]MachineRole, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BareMetalMachineProviderConfig.
func (in *BareMetalMachineProviderConfig) DeepCopy() *BareMetalMachineProviderConfig {
	if in == nil {
		return nil
	}
	out := new(BareMetalMachineProviderConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *BareMetalMachineProviderConfig) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BareMetalMachineProviderConfigList) DeepCopyInto(out *BareMetalMachineProviderConfigList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]BareMetalMachineProviderConfig, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BareMetalMachineProviderConfigList.
func (in *BareMetalMachineProviderConfigList) DeepCopy() *BareMetalMachineProviderConfigList {
	if in == nil {
		return nil
	}
	out := new(BareMetalMachineProviderConfigList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *BareMetalMachineProviderConfigList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FencingConfig) DeepCopyInto(out *FencingConfig) {
	*out = *in
	if in.AgentOptions != nil {
		in, out := &in.AgentOptions, &out.AgentOptions
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.AgentSecret != nil {
		in, out := &in.AgentSecret, &out.AgentSecret
		if *in == nil {
			*out = nil
		} else {
			*out = new(v1.Secret)
			(*in).DeepCopyInto(*out)
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FencingConfig.
func (in *FencingConfig) DeepCopy() *FencingConfig {
	if in == nil {
		return nil
	}
	out := new(FencingConfig)
	in.DeepCopyInto(out)
	return out
}
